src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function isBookableDates() {
        //Vérifier la disponibilité des dates
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\EqualTo;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Un utilisateur possède déjà cette adresse email"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="Veuillez saisir un Nom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="Veuillez saisir un Prénom")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(min=20, minMessage="Votre introduction doit faire plus de 20 caractères !")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez saisir une introduction")
     * @Assert\Length(min=10,minMessage="Votre introduction doit contenir au moin 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text", length=255)
     * @Assert\NotBlank(message="Veuillez saisir une description")
     * @Assert\Length(min=100,minMessage="Votre description doit faire au moin 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @Assert\Email
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="Veuillez saisir un mot de passe ")
     * @Assert\Length(min=3, max=20, minMessage="Le mot de passe doit faire plus de 6 caractères !",
     *                                maxMessage="Le mot de passe ne peut pas faire plus de 4096 caractères !")
     */
    private $password;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function getFullName() {
        return "{$this->firstName} {$this->lastName}";

    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Get the value of firstName
     */ 
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Set the value of firstName
     *
     * @return  self
     */ 
    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get the value of lastName
     */ 
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * Set the value of lastName
     *
     * @return  self
     */ 
    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get the value of picture
     */ 
    public function getPicture(): ?string
    {
        return $this->picture;
    }

    /**
     * Set the value of picture
     *
     * @return  self
     */ 
    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

     /**
     * Get the value of introduction
     */ 
    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    /**
     * Set the value of introduction
     *
     * @return  self
     */ 
    public function setIntroduction(?string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

        /**
     * Get the value of description
     */ 
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Set the value of description
     *
     * @return  self
     */ 
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Permet d'initialiser le slug
     * 
     * @ORM\PrePersist
     * 
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initialize() {
        if(empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    /**
     * Get the value of slug
     */ 
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * Set the value of slug
     *
     * @return  self
     */ 
    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get the value of email
     */ 
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Set the value of email
     *
     * @return  self
     */ 
    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        if(empty($roles)) {
            $roles[] = 'ROLE_USER';
        }
        // guarantee every user at least has ROLE_USER

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return 
            $this->firstName .
            $this->lastName .
            $this->picture .
            $this->introduction .
            $this->description .
            $this->email;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate', DateType::class, $this->getConfiguration("Date d'arrivée",
            'La date à laquelle vous comptez arriver', ["widget" =>"single_text"]))
            ->add('endDate', DateType::class, $this->getConfiguration("Date de départ",
            'La date à laquelle vous quittez les lieux', ["widget" =>"single_text"]))
            ->add('comment', TextareaType::class, $this->getConfiguration(false,
            "Si vous avez un commentaire, n'ezitez pas à en faire part !"))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/booking/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad,Request $request,ObjectManager $manager): Response
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();

            $booking->setBooker($user)
                    ->setAd($ad);

            if(!$booking->isBookableDates()) {
                $this->addFlash(
                    'warning', 
                    "Les dates que vous avez choisie ne peuvent pas être réservées : elles sont déjà prises."
                );
            } else {
                $this->manager->persist($booking);
                $this->manager->flush();

                return $this->redirectToRoute('booking/book.html.twig', [
                    'ad' => $ad,
                    'form' => $form->createView()
                ]);
            }
        }

        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher la page d'une reservation
     * 
     * @IsGranted("ROLE_USER")
     * @Route("/booking/{id}", name="booking_show", methods={"GET"}, requirements={"id":"\d+"})
     * 
     * @param Booking $booking
     * @param Requets $request
     * @param ObjectManager $manager
     * @return Response
     */
    public function show(Booking $booking, Request $request, ObjectManager $manager): Response
    {
        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setAd($booking->getAd())
                    ->setAuthor($this->getUser());

            $this->manager->persist($comment);
            $this->manager->flush();

            $this->addFlash(
                'success', 
                "Votre commentaire a bien été pris en compte !"
            );
        }

        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservez l'annonce : {{ad.title}}{% endblock %}

{% block body %}
    <div class="container">
        <h1>Reservez pour l'annonce : {{ad.title}}</h1>

        <p>Vous êtes sur le point de reserver l'annonce de <strong>{{ad.author.fullName}}</strong>,
        Dites nous tous, on s'occupe du reste !</p>

        {{form_start(form)}}
        <div class="alert alert-light">
            <h2>Commencez par nous dire quelles sont les dates qui vous intéressent !</h2>
            <div class="row">
                <div class="col">
                    {{ form_row(form.startDate) }}
                </div>
                <div class="col">
                    {{ form_row(form.endDate) }}
                </div>
            </div>
        </div>
        <h4>Montant du séjour : <span id="amount">...</span> &euro;</h4>
        <span id="days">Nuit à {{ ad.price }} / nuit</span>

        <h2>Vous avez un commentaire ?</h2>
        {{ form_row(form.comment) }}

        <h2>Vous avez terminé !</h2>
        <p>Vacances de rêve ? Hébergement pour le boulot ? Peut importe, on est avec vous !</p>
        
        <button type="submit" class="btn btn-success">
            Je réserve !
        </button>
        
        {{form_end(form)}}
    </div>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservez l'annonce : {{ad.title}}{% endblock %}

{% block body %}
{% set ad = booking.ad %}
{% set author = ad.author %}
    <div class="container">
      <h1>Votre reservation (n°{{booking.id}})</h1>

      {% if app.request.query.get('withAlert') %}
        <div class="alert alert-success">
            <h4 class="alert-heading">Bravo !</h4>
            <p>
                Votre réservation auprès de
                <strong>
                <a href="{{ path("user_show", {'slug': author.slug}) }}"></a>
                </strong>
                pour l'annonce
                <strong>
                    <a href="{{ path("ad_show", {'id': ad.id}) }}">{{ ad.title }}</a>
                </strong>
                a bien été prise en compte !
            </p>
        </div>
      {% endif %}
      <div class="row">
        <div class="col">
            <div class="alert alert-light">
                <h2>Détails</h2>
                <dl class="row">
                    <dt class="col-md-4">Numéro</dt>
                    <dd class="col-md-8">{{ booking.id }}</dd>
                    <dt class="col-md-4">Date d'arrivée</dt>
                    <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
                    <dt class="col-md-4">Date de départ</dt>
                    <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
                    <dt class="col-md-4">Numbre de nuits</dt>
                    <dd class="col-md-8">{{ booking.duration }}</dd>
                    <dt class="col-md-4">Montant total</dt>
                    <dd class="col-md-8">{{ booking.amount }} &euro;</dd>
                    <dt class="col-md-4">Commentaire</dt>
                    <dd class="col-md-8">{{ booking.comment | default('Auncun commentaire')}}</dd>
                </dl>

                <hr>

                <h2 class="alert-heading">Votre hôte</h2>

                <div class="row mb-3">
                    <div class="col-3">
                        <img src="{{author.picture}}" class="avatar avatar-medium" 
                        alt="Avatar de {{author.fullName}}">
                    </div>
                    <div class="col-9">
                        <h4>
                            <a href="{{ path("user_show", {'id': author.id}) }}">{{ author.fullName }}</a>
                        </h4>

                        <span class="badge badge-primary">{{ author.ads|length }} annonces</span>
                    </div>
                </div>
            </div>
            {{ author.description | raw }}

            <a href="{{ path("user_show", {'id': author.id}) }}" 
                class="btn btn-primary">Plus d'infos sur {{ author.firstName }}
            </a>
            <div class="alert alert-light" id="comment">
                <h2 class="alert-heading">Votre avis compte !</h2>
                {% if date() > date(booking.endDate) %}
                    {% set comment = booking.ad.commentFromAuthor(app.user) %}
                    {% if comment is not null %}
                        <blockquote>
                            {{ comment.content }}
                        </blockquote>

                        <strong>Note : </strong> {% include "partials/rating.html.twig" with {'rating': comment.rating} %}
                    {% else %} 
                        {{ form_start(form) }}
                        {{ form_widget(form) }}
                        <button type="submit" class="btn btn-success">Confirmer !</button>
                        {{ form_start(form) }}
                    {% endif %}
                {% else %}
                    <p>Vous ne pourrez pas noter cette annoonce tant que votre voyage ne sera pas complet</p>
                {% endif %}
            </div>
        </div>
        <div class="col">
            <div class="alert alert-light">
                <h2 class="alert-heading">Votre hébergement</h2>
                <h4>
                    <a href="{{ path("ad_show", {'id': ad.id}) }}">{{ ad.title }}</a>
                </h4>

                <img src="{{ad.coverImage}}" class="img-fluid" 
                        alt="Image de {{ad.tilte}}">
            </div>
        </div>
      </div>
    </div>
{% endblock %}